apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: observability-operatorgroup
  namespace: NAMESPACE
spec:
  targetNamespaces:
   - NAMESPACE
---

apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus-operator
  namespace: NAMESPACE
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.56.3
  thanos:
    baseImage: quay.io/thanos/thanos
    objectStorageConfig:
      key: thanos.yml
      name: thanos-objstore-config
    version: v0.8.1